//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioWebGCM.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://mytest.com/")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoC2DMField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdUsuario {
            get {
                return this.IdUsuarioField;
            }
            set {
                if ((this.IdUsuarioField.Equals(value) != true)) {
                    this.IdUsuarioField = value;
                    this.RaisePropertyChanged("IdUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NombreUsuario {
            get {
                return this.NombreUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreUsuarioField, value) != true)) {
                    this.NombreUsuarioField = value;
                    this.RaisePropertyChanged("NombreUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CodigoC2DM {
            get {
                return this.CodigoC2DMField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoC2DMField, value) != true)) {
                    this.CodigoC2DMField = value;
                    this.RaisePropertyChanged("CodigoC2DM");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://mytest.com/", ConfigurationName="ServiceReference1.ServicioClientesSoap")]
    public interface ServicioClientesSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mytest.com/Add", ReplyAction="*")]
        int Add(int a, int b);
        
        // CODEGEN: Generating message contract since element name usuario from namespace http://mytest.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://mytest.com/RegistroUsuario", ReplyAction="*")]
        ServicioWebGCM.ServiceReference1.RegistroUsuarioResponse RegistroUsuario(ServicioWebGCM.ServiceReference1.RegistroUsuarioRequest request);
        
        // CODEGEN: Generating message contract since element name usuario from namespace http://mytest.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://mytest.com/CodigoUsuario", ReplyAction="*")]
        ServicioWebGCM.ServiceReference1.CodigoUsuarioResponse CodigoUsuario(ServicioWebGCM.ServiceReference1.CodigoUsuarioRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistroUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistroUsuario", Namespace="http://mytest.com/", Order=0)]
        public ServicioWebGCM.ServiceReference1.RegistroUsuarioRequestBody Body;
        
        public RegistroUsuarioRequest() {
        }
        
        public RegistroUsuarioRequest(ServicioWebGCM.ServiceReference1.RegistroUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://mytest.com/")]
    public partial class RegistroUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string regGCM;
        
        public RegistroUsuarioRequestBody() {
        }
        
        public RegistroUsuarioRequestBody(string usuario, string regGCM) {
            this.usuario = usuario;
            this.regGCM = regGCM;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistroUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistroUsuarioResponse", Namespace="http://mytest.com/", Order=0)]
        public ServicioWebGCM.ServiceReference1.RegistroUsuarioResponseBody Body;
        
        public RegistroUsuarioResponse() {
        }
        
        public RegistroUsuarioResponse(ServicioWebGCM.ServiceReference1.RegistroUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://mytest.com/")]
    public partial class RegistroUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int RegistroUsuarioResult;
        
        public RegistroUsuarioResponseBody() {
        }
        
        public RegistroUsuarioResponseBody(int RegistroUsuarioResult) {
            this.RegistroUsuarioResult = RegistroUsuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CodigoUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CodigoUsuario", Namespace="http://mytest.com/", Order=0)]
        public ServicioWebGCM.ServiceReference1.CodigoUsuarioRequestBody Body;
        
        public CodigoUsuarioRequest() {
        }
        
        public CodigoUsuarioRequest(ServicioWebGCM.ServiceReference1.CodigoUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://mytest.com/")]
    public partial class CodigoUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        public CodigoUsuarioRequestBody() {
        }
        
        public CodigoUsuarioRequestBody(string usuario) {
            this.usuario = usuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CodigoUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CodigoUsuarioResponse", Namespace="http://mytest.com/", Order=0)]
        public ServicioWebGCM.ServiceReference1.CodigoUsuarioResponseBody Body;
        
        public CodigoUsuarioResponse() {
        }
        
        public CodigoUsuarioResponse(ServicioWebGCM.ServiceReference1.CodigoUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://mytest.com/")]
    public partial class CodigoUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServicioWebGCM.ServiceReference1.User CodigoUsuarioResult;
        
        public CodigoUsuarioResponseBody() {
        }
        
        public CodigoUsuarioResponseBody(ServicioWebGCM.ServiceReference1.User CodigoUsuarioResult) {
            this.CodigoUsuarioResult = CodigoUsuarioResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioClientesSoapChannel : ServicioWebGCM.ServiceReference1.ServicioClientesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioClientesSoapClient : System.ServiceModel.ClientBase<ServicioWebGCM.ServiceReference1.ServicioClientesSoap>, ServicioWebGCM.ServiceReference1.ServicioClientesSoap {
        
        public ServicioClientesSoapClient() {
        }
        
        public ServicioClientesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioClientesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioClientesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioClientesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Add(int a, int b) {
            return base.Channel.Add(a, b);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServicioWebGCM.ServiceReference1.RegistroUsuarioResponse ServicioWebGCM.ServiceReference1.ServicioClientesSoap.RegistroUsuario(ServicioWebGCM.ServiceReference1.RegistroUsuarioRequest request) {
            return base.Channel.RegistroUsuario(request);
        }
        
        public int RegistroUsuario(string usuario, string regGCM) {
            ServicioWebGCM.ServiceReference1.RegistroUsuarioRequest inValue = new ServicioWebGCM.ServiceReference1.RegistroUsuarioRequest();
            inValue.Body = new ServicioWebGCM.ServiceReference1.RegistroUsuarioRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.regGCM = regGCM;
            ServicioWebGCM.ServiceReference1.RegistroUsuarioResponse retVal = ((ServicioWebGCM.ServiceReference1.ServicioClientesSoap)(this)).RegistroUsuario(inValue);
            return retVal.Body.RegistroUsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServicioWebGCM.ServiceReference1.CodigoUsuarioResponse ServicioWebGCM.ServiceReference1.ServicioClientesSoap.CodigoUsuario(ServicioWebGCM.ServiceReference1.CodigoUsuarioRequest request) {
            return base.Channel.CodigoUsuario(request);
        }
        
        public ServicioWebGCM.ServiceReference1.User CodigoUsuario(string usuario) {
            ServicioWebGCM.ServiceReference1.CodigoUsuarioRequest inValue = new ServicioWebGCM.ServiceReference1.CodigoUsuarioRequest();
            inValue.Body = new ServicioWebGCM.ServiceReference1.CodigoUsuarioRequestBody();
            inValue.Body.usuario = usuario;
            ServicioWebGCM.ServiceReference1.CodigoUsuarioResponse retVal = ((ServicioWebGCM.ServiceReference1.ServicioClientesSoap)(this)).CodigoUsuario(inValue);
            return retVal.Body.CodigoUsuarioResult;
        }
    }
}
